AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AI Career Coach - Backend Spring Boot, Frontend React, Bedrock & DynamoDB.

Globals:
  Function:
    Timeout: 60 # Tăng lên 60s vì gọi AI Bedrock có thể lâu
    MemorySize: 2048 # Java cần RAM khá để chạy mượt
    Runtime: java17
    Architectures: [x86_64]
    Environment:
      Variables:
        TABLE_NAME: !Ref CoreTable
        # ID của model Bedrock (Claude 3 Haiku)
        BEDROCK_MODEL_ID: "anthropic.claude-3-haiku-20240307-v1:0"

Resources:
  # =================================================================
  # 1. DATABASE (Single Table Design)
  # =================================================================
  CoreTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AICareerCoachDB
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1_PK
          AttributeType: S
        - AttributeName: GSI1_SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1_PK
              KeyType: HASH
            - AttributeName: GSI1_SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # =================================================================
  # 2. AUTHENTICATION (Cognito)
  # =================================================================
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: CareerCoachUsers
      AutoVerifiedAttributes: [email]
      UsernameAttributes: [email]
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      # Kích hoạt Trigger sau khi đăng ký để lưu vào DynamoDB
      LambdaConfig:
        PostConfirmation: !GetAtt PostSignupTriggerFunction.Arn

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ReactClient
      UserPoolId: !Ref UserPool
      GenerateSecret: false # Web App (React) không dùng Secret
      ExplicitAuthFlows: [ALLOW_USER_SRP_AUTH, ALLOW_REFRESH_TOKEN_AUTH]

  # Lambda nhỏ (NodeJS) để hứng sự kiện đăng ký và lưu user vào DB
  # (Dùng Nodejs cho cái này vì nó khởi động cực nhanh và nhẹ)
  PostSignupTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 5
      Handler: index.handler
      InlineCode: |
        const { DynamoDBClient, PutItemCommand } = require("@aws-sdk/client-dynamodb");
        const client = new DynamoDBClient({});
        exports.handler = async (event) => {
          if (event.triggerSource === "PostConfirmation_ConfirmSignUp") {
            const userId = event.request.userAttributes.sub;
            const email = event.request.userAttributes.email;
            const params = {
              TableName: process.env.TABLE_NAME,
              Item: {
                PK: { S: `USER#${userId}` },
                SK: { S: "METADATA" },
                email: { S: email },
                createdAt: { S: new Date().toISOString() }
              }
            };
            try { await client.send(new PutItemCommand(params)); } 
            catch (err) { console.error(err); }
          }
          return event;
        };
      Environment:
        Variables:
          TABLE_NAME: !Ref CoreTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CoreTable

  # Cấp quyền cho Cognito được gọi Lambda Trigger
  PostSignupTriggerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PostSignupTriggerFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: !GetAtt UserPool.Arn

  # =================================================================
  # 3. API GATEWAY (HTTP API)
  # =================================================================
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*" # Sau này đổi thành domain thật của CloudFront
        AllowMethods: [GET, POST, PUT, DELETE, OPTIONS]
        AllowHeaders: [Authorization, Content-Type]
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}"
              audience: [!Ref UserPoolClient]

  # =================================================================
  # 4. BACKEND (Spring Boot Monolith Lambda)
  # =================================================================
  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/ # Thư mục chứa code Java
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      SnapStart: # Tăng tốc khởi động Java
        ApplyOn: PublishedVersions
      Policies:
        # Quyền đọc/ghi DB
        - DynamoDBCrudPolicy:
            TableName: !Ref CoreTable
        # Quyền gọi AI Bedrock
        - Statement:
            - Effect: Allow
              Action: bedrock:InvokeModel
              Resource: "*" # Hoặc cụ thể ARN của model Claude 3
      Events:
        ApiRequest:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{proxy+} # Hứng tất cả request (resume, interview...)
            Method: ANY

  # =================================================================
  # 5. FRONTEND HOSTING (S3 + CloudFront)
  # =================================================================
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  FrontendOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "Access S3 bucket content only through CloudFront"

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront::user/CloudFront Origin Access Identity ${FrontendOAI}"
            Action: "s3:GetObject"
            Resource: !Sub "${FrontendBucket.Arn}/*"

  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - DomainName: !GetAtt FrontendBucket.DomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${FrontendOAI}"
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        # SPA Routing: Nếu không tìm thấy file, trả về index.html để React Router xử lý
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

Outputs:
  ApiEndpoint:
    Description: "API URL để dán vào Frontend .env"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  CognitoUserPoolId:
    Description: "User Pool ID"
    Value: !Ref UserPool
  CognitoClientId:
    Description: "App Client ID"
    Value: !Ref UserPoolClient
  WebsiteURL:
    Description: "URL trang web React của bạn"
    Value: !GetAtt FrontendDistribution.DomainName