AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AI Career Coach - Backend Spring Boot, Frontend React, Bedrock & DynamoDB.

Globals:
  Function:
    Timeout: 60 # Tăng lên 60s vì gọi AI Bedrock có thể lâu
    MemorySize: 2048 # Java cần RAM khá để chạy mượt
    Runtime: java17
    Architectures: [x86_64]
    Environment:
      Variables:
        TABLE_NAME: !Ref CoreTable
        # ID của model Bedrock (Claude 3 Haiku)
        BEDROCK_MODEL_ID: "anthropic.claude-3-haiku-20240307-v1:0"

Resources:
  # =================================================================
  # 1. DATABASE (Single Table Design)
  # =================================================================
  CoreTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AICareerCoachDB
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1_PK
          AttributeType: S
        - AttributeName: GSI1_SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1_PK
              KeyType: HASH
            - AttributeName: GSI1_SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # =================================================================
  # 2. AUTHENTICATION (Cognito)
  # =================================================================
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: CareerCoachUsers
      AutoVerifiedAttributes: [email]
      UsernameAttributes: [email]
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      # Kích hoạt Trigger sau khi đăng ký để lưu vào DynamoDB
      LambdaConfig:
        PostConfirmation: !GetAtt PostSignupTriggerFunction.Arn

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ReactClient
      UserPoolId: !Ref UserPool
      GenerateSecret: false # Web App (React) không dùng Secret
      ExplicitAuthFlows: [ALLOW_USER_SRP_AUTH, ALLOW_REFRESH_TOKEN_AUTH]

  # Lambda nhỏ (NodeJS) để hứng sự kiện đăng ký và lưu user vào DB
  # (Dùng Nodejs cho cái này vì nó khởi động cực nhanh và nhẹ)
  PostSignupTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 5
      Handler: index.handler
      InlineCode: |
        const { DynamoDBClient, PutItemCommand } = require("@aws-sdk/client-dynamodb");
        const client = new DynamoDBClient({});
        exports.handler = async (event) => {
          if (event.triggerSource === "PostConfirmation_ConfirmSignUp") {
            const userId = event.request.userAttributes.sub;
            const email = event.request.userAttributes.email;
            const params = {
              TableName: process.env.TABLE_NAME,
              Item: {
                PK: { S: `USER#${userId}` },
                SK: { S: "METADATA" },
                email: { S: email },
                createdAt: { S: new Date().toISOString() }
              }
            };
            try { await client.send(new PutItemCommand(params)); } 
            catch (err) { console.error(err); }
          }
          return event;
        };
      Environment:
        Variables:
          TABLE_NAME: !Ref CoreTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CoreTable

  # Cấp quyền cho Cognito được gọi Lambda Trigger
  PostSignupTriggerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PostSignupTriggerFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: !GetAtt UserPool.Arn

  # =================================================================
  # 3. API GATEWAY (HTTP API)
  # =================================================================
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*" # Sau này đổi thành domain thật của CloudFront
        AllowMethods: [GET, POST, PUT, DELETE, OPTIONS]
        AllowHeaders: [Authorization, Content-Type]
      Auth:
        #DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}"
              audience: [!Ref UserPoolClient]

  # =================================================================
  # 4. BACKEND
  # =================================================================
  # =================================================================
  # LAMBDA 1: QUẢN LÝ USER PROFILE & ONBOARDING
  # =================================================================
  UserProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/target/backend-0.0.1-SNAPSHOT-aws.jar
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CoreTable
      Environment:
        Variables:
          TABLE_NAME: !Ref CoreTable
          # Chỉ chạy hàm profileHandler
          SPRING_CLOUD_FUNCTION_DEFINITION: profileHandler
      Events:
        GetProfile:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /profile
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
        UpdateProfile:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /profile
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer
        GetOnboarding:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /onboarding
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

  # =================================================================
  # LAMBDA 2: QUẢN LÝ INDUSTRY INSIGHTS & AI
  # =================================================================
  IndustryInsightFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/target/backend-0.0.1-SNAPSHOT-aws.jar
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Timeout: 60 # Tăng Timeout vì gọi AI Bedrock có thể lâu
      MemorySize: 2048
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CoreTable
        # Cấp quyền Bedrock chỉ cho hàm này (Bảo mật hơn)
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
                # Thêm quyền Marketplace để sửa lỗi AccessDenied
                - aws-marketplace:ViewSubscriptions
                - aws-marketplace:Subscribe
                - aws-marketplace:Unsubscribe
              Resource: "*"
      Environment:
        Variables:
          TABLE_NAME: !Ref CoreTable
          BEDROCK_MODEL_ID: "anthropic.claude-3-haiku-20240307-v1:0"
          # Chỉ chạy hàm industryInsightHandler
          SPRING_CLOUD_FUNCTION_DEFINITION: industryInsightHandler
      Events:
        GetIndustryInsights:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /industry-insights
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
  # =================================================================
  # LAMBDA 3: QUẢN LÝ RESUME & AI WRITING
  # =================================================================
  ResumeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/target/backend-0.0.1-SNAPSHOT-aws.jar
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Timeout: 60 # AI Improve cần thời gian
      MemorySize: 2048
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CoreTable
        # Cấp quyền Bedrock để Improve Resume
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
                # Thêm quyền Marketplace để sửa lỗi AccessDenied
                - aws-marketplace:ViewSubscriptions
                - aws-marketplace:Subscribe
                - aws-marketplace:Unsubscribe
              Resource: "*"
      Environment:
        Variables:
          TABLE_NAME: !Ref CoreTable
          BEDROCK_MODEL_ID: "anthropic.claude-3-haiku-20240307-v1:0"
          # Chỉ chạy hàm resumeHandler
          SPRING_CLOUD_FUNCTION_DEFINITION: resumeHandler
      Events:
        GetResume:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /resume
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
        SaveResume:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /resume
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer
        ImproveResume:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /resume/improve
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer
  # =================================================================
  # LAMBDA 4: QUẢN LÝ COVER LETTER (CRUD + AI)
  # =================================================================
  CoverLetterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/target/backend-0.0.1-SNAPSHOT-aws.jar
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Timeout: 60 # Gọi AI nên cần timeout lâu
      MemorySize: 2048
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CoreTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
                # Thêm quyền Marketplace để sửa lỗi AccessDenied
                - aws-marketplace:ViewSubscriptions
                - aws-marketplace:Subscribe
                - aws-marketplace:Unsubscribe
              Resource: "*"
      Environment:
        Variables:
          TABLE_NAME: !Ref CoreTable
          BEDROCK_MODEL_ID: "anthropic.claude-3-haiku-20240307-v1:0"
          # Chạy hàm coverLetterHandler
          SPRING_CLOUD_FUNCTION_DEFINITION: coverLetterHandler
      Events:
        # 1. Generate (POST)
        GenerateCoverLetter:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /cover-letters
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

        # 2. List All (GET)
        ListCoverLetters:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /cover-letters
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

        # 3. Get One (GET /{id})
        GetOneCoverLetter:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /cover-letters/{id}
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

        # 4. Delete (DELETE /{id})
        DeleteCoverLetter:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /cover-letters/{id}
            Method: DELETE
            Auth:
              Authorizer: CognitoAuthorizer
  # =================================================================
  # LAMBDA 5: QUẢN LÝ INTERVIEW & ASSESSMENT
  # =================================================================
  InterviewFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/target/backend-0.0.1-SNAPSHOT-aws.jar
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Timeout: 60 # Gọi AI tạo quiz mất thời gian
      MemorySize: 2048
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CoreTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
                # Thêm quyền Marketplace để sửa lỗi AccessDenied
                - aws-marketplace:ViewSubscriptions
                - aws-marketplace:Subscribe
                - aws-marketplace:Unsubscribe
              Resource: "*"
      Environment:
        Variables:
          TABLE_NAME: !Ref CoreTable
          BEDROCK_MODEL_ID: "anthropic.claude-3-haiku-20240307-v1:0"
          # Chạy hàm assessmentHandler
          SPRING_CLOUD_FUNCTION_DEFINITION: assessmentHandler
      Events:
        GenerateQuiz:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /interview/generate
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer
        SaveQuiz:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /interview/save
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer
        GetHistory:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /interview/history
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
  # =================================================================
  # 5. FRONTEND HOSTING (S3 + CloudFront + OAC Security)
  # =================================================================
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "career-coach-frontend-${AWS::AccountId}" # Thêm ID tài khoản để chắc chắn không trùng tên
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Cấu hình bảo mật mới (OAC) - Thay thế cho OAI cũ bị lỗi
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: "Access Control for CV Analyzer"
        Name: !Sub "OAC-${FrontendBucket}"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowCloudFrontServicePrincipal"
            Effect: Allow
            Principal:
              Service: "cloudfront.amazonaws.com" # Dùng Service Principal chuẩn (Luôn tồn tại)
            Action: "s3:GetObject"
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                "AWS:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${FrontendDistribution}"

  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - DomainName: !GetAtt FrontendBucket.RegionalDomainName # Lưu ý dùng RegionalDomainName
            Id: S3Origin
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id # Trỏ vào OAC mới
            S3OriginConfig:
              OriginAccessIdentity: "" # Để trống dòng này vì đã dùng OAC
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD, OPTIONS]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

Outputs:
  ApiEndpoint:
    Description: "API URL để dán vào Frontend .env"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  CognitoUserPoolId:
    Description: "User Pool ID"
    Value: !Ref UserPool
  CognitoClientId:
    Description: "App Client ID"
    Value: !Ref UserPoolClient
  WebsiteURL:
    Description: "URL trang web React của bạn (CloudFront)"
    Value: !GetAtt FrontendDistribution.DomainName
  S3BucketName:
    Description: "Tên Bucket để upload code Frontend"
    Value: !Ref FrontendBucket